apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: ecommerce-backend
        image: pavankolasani719/ecommerce-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
spec:
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
