apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
spec:
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 5000  # Port for your backend service
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
spec:
  selector:
    app: ecommerce-frontend
  ports:
    - protocol: TCP
      port: 80  # Port for your frontend service
      targetPort: 80
  type: NodePort  # Expose it outside the cluster
